### ISSUE TITLE
Is master branch ready to production?

### ISSUE THREAD

**Issue by alopezh** [CrowdNotifier/crowdnotifier-sdk-ios#2]
Hi, 

We are using CrowdNotifier to implement a QR based notification solution of exposed events. We see the following disclaimer in the descriptio:

> Work in Progress
The CrowdNotifier protocol is undergoing changes to improve its security and privacy properties. See CrowdNotifier for updates on the design. This SDK will be updated to reflect these changes.
The CrowdNotifierSDK for Android contains alpha-quality code only and is not yet complete. We are continuing the development of this library, and the API is likely to change. The library has not yet been reviewed or audited for security and compatibility.

But we don't see any commit in recent months. Is the code in master branch ready to production?

Additionaly when we try to use v2.0 tag in SPM we get the following error: 
> Failed to resolve dependencies: because no versions of crowdnotifier-sdk-ios match the requirement 2.0.0..<3.0.0 and root depends on crowdnotifier-sdk-ios 2.0.0..<3.0.0, version solving failed.

So we are using master branch to set up the dependency. Is this ok?

Regards

**Comment by ubfelix** [comment]
Hi @alopezh 

Thank you for pointing out the problem with using a version-based requirement in SPM. We have fixed this in version 2.0.1.
