### ISSUE TITLE
Error when distributing AdHoc ipa that contains CrowdNotifier as dependency

### ISSUE THREAD

**Issue by alopezh** [CrowdNotifier/crowdnotifier-sdk-ios#4]
When I try to generate the ad-hoc ipa for an application containing CrowdNotifier as dependency I receive an error:

![imagen](https://user-images.githubusercontent.com/2195286/113564534-d8bbf200-9609-11eb-8549-765950491a4d.png)

I can find very little information in the logs, the few lines that can give me a clue are:

> Assertion failed: Expected 3 archs in otool output:
> Archive : /var/folders/c6/n8j765_j6b7d_d11fjvxfwyc0000gn/T/IDEDistributionOptionThinning.~~~VTvms3/Payload/test.app/Frameworks/libmcl.a (architecture armv7)
> /var/folders/c6/n8j765_j6b7d_d11fjvxfwyc0000gn/T/IDEDistributionOptionThinning.~~~VTvms3/Payload/test.app/Frameworks/libmcl.a(fp.cpp.o) (architecture armv7):

If I run a validate app from the organizer i get the following errors:
- Invalid swift support the file libmcl.a doesn´t have the correct file type
- Invalid swift support the file Clibsodium.a doesn´t have the corarect file type
- Invalid bundle structure: the binary file libmcl.a is not permitted your app can't contain standalone executables or libraries
- Invalid bundle structure: the binary file Clibsodium.a is not permitted your app can't contain standalone executables or libraries

If I manually open the ipa and remove those .a files then I can distribute the ad-hoc version of the app. And apparently everything runs ok!

I have added the following configurations to allow compiling:
- Other linker flags: -lstdc++
- Allow bitcode: No

Did I miss any configuration that is needed? I've checked NotifyMe source code and I can´t find what is missing.

Regards

**Comment by UBaggeler** [comment]
Hi @alopezh 

There is a known bug in the current Xcode SPM integration with static `binaryTargets`. Xcode copies the .a-Files into the resulting product into the `/Frameworks` folder (additionally to linking them into the binary). 

Google's SPM package for Firebase has the same issue: https://github.com/firebase/firebase-ios-sdk/issues/6472

We worked around this limitation in NotifyMe by adding a post-action to the scheme (https://github.com/notifyme-app/notifyme-app-ios/commit/7b9cbc0a0f5b21aec69fd0ea7d36c5bfa160fba1) which removes these files from the resulting app. 

I hope this helps!

Best,
Fabian

**Comment by UBaggeler** [comment]
Related: https://developer.apple.com/documentation/xcode-release-notes/xcode-12_4-release-notes#Swift-Packages

> * If you use a Swift package with binary dependencies in an app with extensions, the build system incorrectly embeds the binary dependencies alongside the extension in the PlugIns directory, causing validation of the archived app to fail. (69834549) (FB8761306)
>    Workaround: Add a scheme post-build action which removes the embedded binaries from the PlugIns directory after the build, e.g. rm -rf "${TARGET_BUILD_DIR}/${TARGET_NAME}.app"/PlugIns/*.framework.

**Comment by alopezh** [comment]
Thanks, It's working now!

We had to chenge `TARGET_NAME` for `PRODUCT_NAME`. In your case the target is the same as the product so it works, but the folder name is taken from de product name.

```
rm -rf "${TARGET_BUILD_DIR}/${PRODUCT_NAME}.app/Frameworks/libsodium.a"
rm -rf "${TARGET_BUILD_DIR}/${PRODUCT_NAME}.app/Frameworks/libmcl.a"
```
Regards

**Comment by alopezh** [comment]
I close the issue, I've created a pull request modifiing README.md if you want to include this in the documentation.

Thanks again, 
Regards
